# SPDX-License-Identifier: MIT
import subprocess
import argparse
import pandas as pd
import sys
from pathlib import Path

CAM_FILE_TWO_LAYER = "~/SparkFun/SparkFun_Eagle_Settings/cam/sfe-gerb274x-2layer.cam"
CAM_FILE_FOUR_LAYER = "~/SparkFun/SparkFun_Eagle_Settings/cam/sfe-gerb274x-4layer.cam"

# @brief An array of column labels to compare csv files against.
keep_columns = [
    "SparkFun Part Number",
    "Part Description",
    "BOM Quantity",
    "Primary Vendor",
    "Primary Vendor Part Number",
    "Primary Vendor Cost",
]

# @brief An array of strings to compare csv files against.
exclude_labels = ["FD", "TP", "FID", "SJ", "DNP", "JP", "ST"]

# @brief Path fo csv output.
csv_path = "/SparkFun/ContractManufacturingFiles/"

# ███████╗██╗   ██╗███╗   ██╗ ██████╗████████╗██╗ ██████╗ ███╗   ██╗███████╗
# ██╔════╝██║   ██║████╗  ██║██╔════╝╚══██╔══╝██║██╔═══██╗████╗  ██║██╔════╝
# █████╗  ██║   ██║██╔██╗ ██║██║        ██║   ██║██║   ██║██╔██╗ ██║███████╗
# ██╔══╝  ██║   ██║██║╚██╗██║██║        ██║   ██║██║   ██║██║╚██╗██║╚════██║
# ██║     ╚██████╔╝██║ ╚████║╚██████╗   ██║   ██║╚██████╔╝██║ ╚████║███████║
# ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝


# @brief Function takes a path to a csv file. It filters out specific columns within csv
# files generated by Sparkle
# @param path_to_spreadsheet Path to the spreadsheet
# @return nothing
def sparkle_assembly_update(path_to_spreadsheet):
    truncated_path = path_to_spreadsheet.split("/")[-1]
    print(f"\nReading from {truncated_path}\n")
    # Insanely powerful ability to both read a csv, keep specific columns, and sort alphabetically
    # from within one function call.
    new_csv = pd.read_csv(path_to_spreadsheet, usecols=keep_columns).sort_values(
        "SparkFun Part Number"
    )
    print(new_csv)
    # Without the "index = False" line there is an extra column added in column "A" listing the index.
    # of the rows.
    print("Placed here: {0}{1}".format(csv_path, truncated_path))
    new_csv.to_csv("~{0}{1}".format(csv_path, truncated_path), index=False)


# @brief Filters out rows for specific labels of BOMS and CPL csv's generated by the Eagle JLCPCB ULP
# @param path_to_spreadsheet Path to the spreadsheet
# @return nothing
def ulp_csv_update(path_to_spreadsheet):
    # Split by path designators and keep the last split which is the file itself.
    truncated_path = path_to_spreadsheet.split("/")[-1]
    print(f"\nReading from {truncated_path}\n")
    # Read in the given cs, can be position or BOM csv.
    csv_pd = pd.read_csv(path_to_spreadsheet)
    # Return a copy of the csv that removes the rows from the column "Designator" that match the labels within
    # "exclude_labels". Note that this is in fact making a csv that match the labels of the list, but inverts the
    # matching behavior: ~
    updated_csv = csv_pd[~csv_pd["Designator"].str.contains("|".join(exclude_labels))]
    alphabetized_csv = updated_csv.sort_values("Designator")
    # Print it so that we can check it at a glance on the terminal
    print(alphabetized_csv)

    print("Placed here: {0}".format(path_to_spreadsheet))
    alphabetized_csv.to_csv("{0}".format(path_to_spreadsheet), index=False)


def cam_board(board_file, layers=2):
    output_dir = str(board_file.parent) + "/"

    if layers == 2:
        subprocess.run(
            [
                "eagle",
                "-X",
                "-dCAMJOB",
                f"-j{CAM_FILE_TWO_LAYER}",
                f"-o{output_dir}",
                str(board_file),
            ]
        )
    elif layers == 4:
        subprocess.run(
            [
                "eagle",
                "-X",
                "-dCAMJOB",
                f"-j{CAM_FILE_FOUR_LAYER}",
                f"-o{output_dir}",
                str(board_file),
            ]
        )
    else:
        print("Pick number of layers...")


#
# ███╗   ███╗ █████╗ ██╗███╗   ██╗
# ████╗ ████║██╔══██╗██║████╗  ██║
# ██╔████╔██║███████║██║██╔██╗ ██║
# ██║╚██╔╝██║██╔══██║██║██║╚██╗██║
# ██║ ╚═╝ ██║██║  ██║██║██║ ╚████║
# ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝
#
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", action="store_true", help="Cams the given board file")
    parser.add_argument("-s", action="store_true", help="Modifies the given csv file")
    parser.add_argument("directory", help="path to .brd file")
    args = parser.parse_args()

    product_directory = Path(args.directory)

    if args.c:
        for subdir in product_directory.iterdir():
            if subdir.is_dir() and subdir.name == "production":
                ulp_csv_update(subdir)
    if args.s:
        for subdir in product_directory.iterdir():
            if subdir.is_dir() and subdir.name == "Hardware":
                cam_board(subdir)
