# SPDX-License-Identifier: MIT
import subprocess
import argparse
import pandas as pd
import sys
from pathlib import Path
import zipfile

CAM_FILE_TWO_LAYER = (
    "/home/amo/SparkFun/SparkFun_Eagle_Settings/cam/sfe-gerb274x-2layer.cam"
)
CAM_FILE_FOUR_LAYER = "~/SparkFun/SparkFun_Eagle_Settings/cam/sfe-gerb274x-4layer.cam"
PATH_FAB_PLUGIN = "/home/amo/.var/app/org.kicad.KiCad/data/kicad/10.0/3rdparty/plugins/"
FABRICATION_TOOLKIT_MODULE = "com_github_bennymeg_JLC-Plugin-for-KiCad"
# @brief An array of column labels to compare csv files against.
keep_columns = [
    "SparkFun Part Number",
    "Part Description",
    "BOM Quantity",
    "Primary Vendor",
    "Primary Vendor Part Number",
    "Primary Vendor Cost",
]

# @brief An array of strings to compare csv files against.
exclude_labels = ["FD", "TP", "FID", "SJ", "DNP", "JP", "ST"]

layer_suffixes = [
    "GBL",
    "GBO",
    "GBP",
    "GBS",
    "GKO",
    "GTL",
    "GTO",
    "GTP",
    "GTS",
    "TXT",
    "GM1",
    "DRL",
]

layer_list = [
    "F.Cu,In1.Cu,In2.Cu,In3.Cu,In4.Cu,B.Cu,F.Paste,B.Paste,F.Silkscreen,B.Silkscreen,F.Mask,B.Mask,Edge.Cuts"
]

# @brief Path fo csv output.
csv_path = "/SparkFun/ContractManufacturingFiles/"

# ███████╗██╗   ██╗███╗   ██╗ ██████╗████████╗██╗ ██████╗ ███╗   ██╗███████╗
# ██╔════╝██║   ██║████╗  ██║██╔════╝╚══██╔══╝██║██╔═══██╗████╗  ██║██╔════╝
# █████╗  ██║   ██║██╔██╗ ██║██║        ██║   ██║██║   ██║██╔██╗ ██║███████╗
# ██╔══╝  ██║   ██║██║╚██╗██║██║        ██║   ██║██║   ██║██║╚██╗██║╚════██║
# ██║     ╚██████╔╝██║ ╚████║╚██████╗   ██║   ██║╚██████╔╝██║ ╚████║███████║
# ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝


# @brief Function takes a path to a csv file. It filters out specific columns within csv
# files generated by Sparkle
# @param spreadsheet_file Path to the spreadsheet
# @return nothing
def sparkle_assembly_update(spreadsheet_file):
    output_dir = str(spreadsheet_file.parent.parent) + "/Manufacturing/"
    Path(output_dir).mkdir(exist_ok=True)
    print(f"\nReading from {truncated_path}\n")
    # Insanely powerful ability to both read a csv, keep specific columns, and sort alphabetically
    # from within one function call.
    new_csv = pd.read_csv(spreadsheet_file, usecols=keep_columns).sort_values(
        "SparkFun Part Number"
    )
    print(new_csv)
    # Without the "index = False" line there is an extra column added in column "A" listing the index.
    # of the rows.
    print("Placed here: {0}{1}".format(csv_path, truncated_path))
    new_csv.to_csv("~{0}{1}".format(csv_path, truncated_path), index=False)


# @brief Filters out rows for specific labels of BOMS and CPL csv's generated by the Eagle JLCPCB ULP
# @param spreadsheet_file Path to the spreadsheet
# @return nothing
def ulp_csv_update(spreadsheet_file):
    updated_csv_output = (
        str(spreadsheet_file.parent.parent) + "/Manufacturing/" + spreadsheet_file.name
    )

    # Split by path designators and keep the last split which is the file itself.
    print(f"\nReading from {spreadsheet_file}\n")
    # Read in the given cs, can be position or BOM csv.
    csv_pd = pd.read_csv(spreadsheet_file)
    # Return a copy of the csv that removes the rows from the column "Designator" that match the labels within
    # "exclude_labels". Note that this is in fact making a csv that match the labels of the list, but inverts the
    # matching behavior: ~
    updated_csv = csv_pd[~csv_pd["Designator"].str.contains("|".join(exclude_labels))]
    alphabetized_csv = updated_csv.sort_values("Designator")

    # Print it so that we can check it at a glance on the terminal
    print(alphabetized_csv)

    print("Update CSV is here: {0}\n".format(updated_csv_output))
    alphabetized_csv.to_csv(updated_csv_output, index=False)

    if spreadsheet_file.stem == "bom":
        print("Merging BOM and JLCPCB Part Numbers")
        add_jlc_part_numbers_to_csv(spreadsheet_file.parent.parent, updated_csv_output)
    else:
        print("Skipping non-BOM CSV.")


def add_jlc_part_numbers_to_csv(csv_directory, updated_csv_file):
    pg_admin_file = None
    csv_directory_parent = csv_directory.parent
    for file in csv_directory_parent.iterdir():
        if "data" in file.stem:
            pg_admin_file = file
            break

    if pg_admin_file is None:
        print(
            "\n-------\nSkipping\nCould not find data file in {0}\n--------\n".format(
                csv_directory_parent
            )
        )
        return

    print("Found Data File")

    csv_with_part_number = pd.read_csv(pg_admin_file)
    csv_without_part_numbers = pd.read_csv(updated_csv_file)

    if (
        "Value" not in csv_without_part_numbers.columns
        or "Quantity" not in csv_without_part_numbers.columns
    ):
        return

    csv_without_part_numbers["LCSC Part #"] = csv_without_part_numbers.apply(
        lambda row: m.iloc[0]["suppliers_part_number"]
        if len(
            m := csv_with_part_number[
                csv_with_part_number["component_name"].str.contains(
                    str(row["Value"]), regex=False
                )
                & (
                    csv_with_part_number["component_qty"].astype(int)
                    == int(row["Quantity"])
                )
            ]
        )
        == 1
        else None,
        axis=1,
    )

    print("Done merging files.")
    csv_without_part_numbers.to_csv(updated_csv_file, index=False)


def cam_board_eagle(board_file, layers=2):
    output_dir = str(board_file.parent) + "/Manufacturing/"

    if layers == 2:
        subprocess.run(
            [
                "eagle",
                "-X",
                "-dCAMJOB",
                f"-j{CAM_FILE_TWO_LAYER}",
                f"-o{output_dir}",
                str(board_file),
            ]
        )
    elif layers == 4:
        subprocess.run(
            [
                "eagle",
                "-X",
                "-dCAMJOB",
                f"-j{CAM_FILE_FOUR_LAYER}",
                f"-o{output_dir}",
                str(board_file),
            ]
        )
    else:
        print("Pick number of layers...")


# @brief Calls the built in CAMMER from
def cam_board_kicad(board_file):
    output_dir = str(board_file.parent) + "/Manufacturing/"

    subprocess.run(
        [
            "flatpak",
            "run",
            "--command=kicad-cli",
            "org.kicad.KiCad",
            "pcb",
            "export",
            "gerbers",
            "--output",
            output_dir,
            "--layers",
            "F.Cu,In1.Cu,In2.Cu,In3.Cu,In4.Cu,B.Cu,F.Paste,B.Paste,F.Silkscreen,B.Silkscreen,F.Mask,B.Mask,Edge.Cuts",
            str(board_file),
        ]
    )

    subprocess.run(
        [
            "flatpak",
            "run",
            "--command=kicad-cli",
            "org.kicad.KiCad",
            "pcb",
            "export",
            "drill",
            "--output",
            output_dir,
            str(board_file),
        ]
    )


def run_fabricate_plugin_kicad(board_file):
    result = subprocess.run(
        [
            "flatpak",
            "run",
            "--command=bash",
            "org.kicad.KiCad",
            "-c",
            f"cd {PATH_FAB_PLUGIN} && python3 -m {FABRICATION_TOOLKIT_MODULE}.cli -p {str(board_file)}",
        ]
    )

    return result.returncode


#
# ███╗   ███╗ █████╗ ██╗███╗   ██╗
# ████╗ ████║██╔══██╗██║████╗  ██║
# ██╔████╔██║███████║██║██╔██╗ ██║
# ██║╚██╔╝██║██╔══██║██║██║╚██╗██║
# ██║ ╚═╝ ██║██║  ██║██║██║ ╚████║
# ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝
#
if __name__ == "__main__":
    # Put the output of fabrication tool in a known state.
    fabrication_tool_result = -1
    hardware_directory = None
    # Specifying the arguments for the command line
    parser = argparse.ArgumentParser()
    # We have -c for calling caming processes and -s for calling spreadsheet creation
    parser.add_argument("-c", action="store_true", help="Cams the given board file")
    parser.add_argument("-s", action="store_true", help="Modifies the given csv file")
    # The program also expects a directory with which to look for board files and spreasheets.
    # It only needs the top level but requires that the parent folder has a "Hardware" and "production" folder
    # with the expected files within them. The folders are sensitive to these specific cap
    parser.add_argument("directory", help="path to .brd file")
    args = parser.parse_args()

    # First, validate that the given path has a Hardware direcotry
    parent_product_directory = Path(args.directory)
    for subdir in parent_product_directory.iterdir():
        if subdir.is_dir() and subdir.name == "Hardware":
            print("Found Hardware")
            hardware_directory = subdir
            break
        else:
            sys.exit("No Hardware Directory in the given path.")

    # Create the output directory "Manufacturing" within the parent directory given on the command line
    # that the output of cammer and csv creation tool expect.
    manufacturing_directory = str(hardware_directory) + "/Manufacturing/"
    # If it already exists that's fine.
    Path(manufacturing_directory).mkdir(exist_ok=True)

    # This is to satisfy the LSP. It may be possible that we get here somehow?
    assert hardware_directory is not None

    ## Spreadsheet argument
    if args.s:
        for file in hardware_directory.iterdir():
            if file.suffix == ".kicad_pcb":
                print("Running fabrication plugin on KiCad Board File.\n")
                fabrication_tool_result = run_fabricate_plugin_kicad(file)
            elif file.suffix == ".brd":
                print("Unfortunately there is no headles CLI for this process.")
                break
        if fabrication_tool_result == 0:
            print("Checking BOM and Positional Data.")
            for subdir in hardware_directory.iterdir():
                if subdir.is_dir() and subdir.name == "production":
                    print("Found correct folder")
                    for file in subdir.iterdir():
                        if file.stem == "bom":
                            print("Found BOM CSV.")
                            ulp_csv_update(file)
                        elif file.stem == "positions":
                            print("Found Positions CSV.")
                            ulp_csv_update(file)
                        else:
                            print("Found extraneous CSV.")
        else:
            print("Fabrication ULP did not succesfully run.")

    if args.c:
        for file in hardware_directory.iterdir():
            if file.suffix == ".kicad_pcb":
                print("Found KiCad file, outputing CAM")
                cam_board_kicad(file)
            elif file.suffix == ".brd":
                print("Found Eagle file, outputing CAM")
                cam_board_eagle(file)

        # Add error checking before running this
        print("Zipping cam files.")
        for subdir in hardware_directory.iterdir():
            if subdir.is_dir() and subdir.name == "Manufacturing":
                with zipfile.ZipFile(
                    subdir / (parent_product_directory.name + ".zip"),
                    "w",
                ) as zf:
                    for file in subdir.iterdir():
                        if file.suffix.lstrip(".").upper() in layer_suffixes:
                            zf.write(file, file.name)
